# -*- coding: utf-8 -*-
"""histogram_stretching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtW07zLkFMpyZ3Ni2MQyFVKoiGQ6DJsl
"""
import cv2
import numpy as np
import matplotlib.pyplot as plt
def histogram_stretching(image, r_min, r_max):
    min_pixel = np.min(image)
    max_pixel = np.max(image)

    stretched_image = (image - min_pixel) * ((r_max - r_min) / (max_pixel - min_pixel)) + r_min
    stretched_image = np.clip(stretched_image, 0, 255)

    return stretched_image.astype(np.uint8)

def histogram(image):
    hist = np.zeros(256, dtype=np.uint8)
    for pixel_value in image.flatten():
        hist[pixel_value] += 1
    return hist
image = cv2.imread('C:\\Users\\Admin\\Downloads\\beautiful-nature-scenery-free-photo (1).jpg')
r_min = 10
r_max = 100
stretched_image = histogram_stretching(image, r_min, r_max)
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(stretched_image)
plt.title('Noisy')
plt.axis('off')

hist_original = histogram(image)
hist_stretched = histogram(stretched_image)

# Plot histograms
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.plot(hist_original, color='b')
plt.title('Original Image Histogram')
plt.xlabel('Pixel Value')
plt.ylabel('Frequency')

plt.subplot(1, 2, 2)
plt.plot(hist_stretched, color='r')
plt.title('Stretched Image Histogram')
plt.xlabel('Pixel Value')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

