# -*- coding: utf-8 -*-
"""mnist_load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8P0t-1yN5he7BBzbpq4TbeWzwsdhqT-
"""

import matplotlib.pyplot as plt
from keras.datasets import mnist
import numpy as np
# Load the MNIST dataset
(_, _), (test_images, _) = mnist.load_data()

# Display a random image from the dataset
plt.imshow(test_images[np.random.randint(len(test_images))], cmap='gray')
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
from keras.datasets import cifar10
import numpy as np
# Load CIFAR-10 dataset
(_, _), (test_images, _) = cifar10.load_data()

# Display a random image from the dataset
plt.imshow(test_images[np.random.randint(len(test_images))])
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist
import numpy as np
# Load Fashion MNIST dataset
(_, _), (test_images, _) = fashion_mnist.load_data()

# Display a random image from the dataset
plt.imshow(test_images[np.random.randint(len(test_images))], cmap='gray')
plt.axis('off')
plt.show()